# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e496dc5b6717a81b80e1149fc20c2c82579725712cca76604475502c7535280c03de8288275f5a249b94529d1395d38c0d7c6a7101b1ee740a9e792899fa48d

test:
  secret_key_base: 72ba0ced00c99e1b949fc9f52dd421130aed110b1cca025b15d4bc67e62255a23795bf1a1bb21fb14667945df5bf014dfff84925f7e310e48bd35c868426b373

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
